[/Script/EngineSettings.GameMapsSettings]
GlobalDefaultGameMode=/Script/Oracle.OracleGameMode
; Editor e jogo abrem direto na vila bonita.
EditorStartupMap=/Game/StylizedIsland/Scenes/Village_Main.Village_Main
GameDefaultMap=/Game/StylizedIsland/Scenes/Village_Main.Village_Main

[/Script/Engine.RendererSettings]
; Lumen + Nanite: padrão AAA definido desde o início
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Lumen.HardwareRayTracing=False
r.Shadow.Virtual.Enable=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.AntiAliasingMethod=4
r.Nanite=1
; Look anime: imagem limpa e nítida
r.DefaultFeature.MotionBlur=False
r.Tonemapper.Sharpen=0.6

[/Script/Engine.PhysicsSettings]
bTickPhysicsAsync=True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/EnhancedInput.EnhancedInputDeveloperSettings]
bEnableDefaultMappingContexts=False

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=5FA9F89847BCAE6364C36DB076ADE6F6
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

